#
# A simple GKE java cronjob docker image.
#
# Install with
#
# $ kubectl apply -f deploy.yaml
#
apiVersion: v1
kind: ConfigMap
metadata:
  name: gcp-cronjob-gke-config-map
  labels:
    app: gcp-cronjob-gke
data:
  VOLUME_PATH: /mnt/volume/
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gcp-cronjob-gke
  labels:
    app: gcp-cronjob-gke
spec:
  schedule: "50 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: gcp-cronjob-gke
            image: gcr.io/neat-responder-323913/gcp-cronjob-gke:latest
            imagePullPolicy: IfNotPresent
            envFrom:
              - configMapRef:
                  name: gcp-cronjob-gke-config-map
            volumeMounts:
              - name: api-volume
                mountPath: "/mnt/volume"
            command:
            - java
            - -jar
            - ./app/cronjob-gke-0.0.1-SNAPSHOT.jar
          restartPolicy: OnFailure
          volumes:
          - name: api-volume
            persistentVolumeClaim:
              claimName: web-app-spring-data-pvc
